name: Build infrastructure
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'gfa-iac/**'
jobs:
  test-infastructure:
    name: Test infastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test build
        run: (cd gfa-iac && npm ci && npm run build) 
      - name: Synthesize CDK
        uses: youyo/aws-cdk-github-actions@v1
        with:
          working_dir: 'gfa-iac'
          cdk_subcommand: >
            synth -c artifactsBucketName=${{ secrets.S3_ARTIFACT_BUCKET }}
                  -c version=${{ steps.pull_request.outputs.number }}
                  -c hostedZoneId=${{ secrets.HOSTED_ZONE_ID }}
                  -c domainName=${{ secrets.DOMAIN_NAME }}
                  -c adminEmail=${{ secrets.ADMIN_EMAIL }}
                  -c sendgridApiKey=${{ secrets.SENDGRID_API_KEY }}
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
